from pathlib import Path

def add_extras(page, write):
    root = Path(__file__).parent
    art = '''<div class="project-art benda-art"><div class="benda-brand"><span class="benda-symbol">+</span> BENDA <small>CPR SERVICES MILWAUKEE</small></div><div class="benda-message"><span>HEALTH EDUCATION / COMMUNITY</span><h3>Knowledge that<br>makes a difference.</h3><div class="benda-courses"><span>CPR & BLS</span><span>First aid</span><span>Healthcare training</span></div></div><div class="benda-art-footer">LEARN. PREPARE. MAKE AN IMPACT.<span>↗</span></div></div>'''
    card = f'''<article class="project-card benda-feature"><a class="art-link" href="benda-cpr.html" aria-label="Explore Benda CPR Services">{art}</a><div class="benda-summary"><div class="project-meta"><span>CLIENT WORK / APR 2024 — SEP 2025</span><span>03</span></div><a class="project-title" href="benda-cpr.html"><h3>Benda CPR Services</h3><span>↗</span></a><p>Web development for a Milwaukee-area health education business, supporting the people behind the training.</p><div class="tags"><span>Web development</span><span>Custom plugins</span><span>Client collaboration</span></div><a class="text-link" href="benda-cpr.html">Explore the project ↗</a></div></article>'''
    for filename in ['index.html', 'chrisWebDev.html']:
        html = (root / filename).read_text(encoding='utf-8')
        marker = '</article></div>'
        assert marker in html
        html = html.replace(marker, '</article>' + card + '</div>', 1)
        write(filename, html)
    write('benda-cpr.html', page('Benda CPR Services — client work', f'''<section class="page-intro wrap"><a class="back-link" href="chrisWebDev.html">← Back to work</a><p class="eyebrow">CLIENT WORK / WEB DEVELOPMENT</p><h1>Practical skills.<br>A meaningful <span class="serif">mission.</span></h1><p>Web development support for Benda CPR Services, a Milwaukee-area business providing CPR certification and health education.</p><a class="button" href="https://bendacprmilwaukee.com/" target="_blank" rel="noopener noreferrer">Visit live website ↗</a></section><section class="wrap case-visual">{art}</section><section class="wrap section case-body"><aside><p class="eyebrow">MY CONTRIBUTION</p><h3>Web Developer</h3><p>Part-time contractor<br>April 2024 — September 2025</p><p>HTML · CSS · JavaScript<br>Custom pages & plugins<br>Testing & troubleshooting</p><small>Project artwork is an editorial illustration, not a screenshot of the live website.</small></aside><div><h2>Supporting the people<br>who help others <span class="serif">prepare.</span></h2><p>Benda’s website introduces its training services and provides routes to course booking. Clear information helps visitors understand the available options and take the next step.</p><h3>Custom development, consistent presentation</h3><p>During my contractor role, I used HTML, CSS, and JavaScript to create custom pages aligned with established design patterns. My work also included developing custom plugins and supporting marketing efforts.</p><h3>Attention beyond the first build</h3><p>I tested the website, identified and recorded bugs, and worked through fixes. That ongoing attention to the customer experience was an important part of my contribution.</p><a class="text-link" href="https://bendacprmilwaukee.com/" target="_blank" rel="noopener noreferrer">See Benda CPR Services live ↗</a></div></section>''', 'Work'))
    photos = [
        ('chris2', 'Chris outdoors beside a tree', 'A little perspective', 'Curiosity, connection, and the person behind the work.'),
        ('chris6', 'Chris seated by a window with a laptop', 'Room to think', 'Space for new ideas and a different point of view.'),
        ('chris3', 'Chris wearing a cap and gown at graduation', 'A milestone worth remembering', 'The foundations of a lifelong learning mindset.'),
        ('chrisFootball1', 'Chris carrying a football in a yellow Bison uniform', 'Built through teamwork', 'Discipline and collaboration extend beyond the field.'),
        ('chrisSoccer2', 'Chris on a soccer field at night', 'Beyond the screen', 'Making time for the things that bring people together.')]
    slides = ''.join(f'''<figure class="gallery-slide" role="group" aria-roledescription="slide" aria-label="{i+1} of {len(photos)}" {"hidden" if i else ""}><img src="assets/gallery-{name}.webp" alt="{alt}" width="1100" height="800"><figcaption><h3>{title}</h3><p>{caption}</p></figcaption></figure>''' for i,(name,alt,title,caption) in enumerate(photos))
    gallery = f'''<section class="section gallery-section"><div class="wrap"><div class="section-heading"><div><p class="eyebrow">04 / BEYOND THE CODE</p><h2>A few moments.<br>A fuller <span class="serif">picture.</span></h2></div><p class="section-description">The experiences, interests, and milestones that shape how I show up in my work.</p></div><div class="photo-gallery" role="region" aria-roledescription="carousel" aria-label="Photos of Chris" tabindex="0">{slides}<div class="gallery-controls" hidden><span class="gallery-status" aria-live="polite" aria-atomic="true">01 / 05</span><div><button type="button" data-gallery-prev aria-label="Previous photo">←</button><button type="button" data-gallery-next aria-label="Next photo">→</button></div></div></div></div></section>'''
    html = (root / 'index.html').read_text(encoding='utf-8')
    write('index.html', html.replace('</main>', gallery + '</main>').replace('</head>', '<script src="gallery.js" defer></script></head>'))
    for filename in ['index.html','chrisWebDev.html','resume.html','brandon-hope.html','enterprise.html','benda-cpr.html','chrisFootball.html','chrisSoccer.html']:
        html = (root / filename).read_text(encoding='utf-8')
        write(filename, html.replace('</head>', '<link rel="stylesheet" href="extras.css"></head>'))
